FROM alpine:latest@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60

LABEL "org.opencontainers.image.source"="https://github.com/pagopa/example-bad-repo-packages"
LABEL "maintainer"="https://pagopa.it"
